GOFRIENDSTest/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('', include('cities.urls')),
]

cities/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    path('', views.IndexView.as_view(template_name='cities/index.html'), name='index'),
    path('cities/', views.CitiesView.as_view(template_name='cities/cities.html'), name='cities'),
    path('create_city/', views.CityCreateView.as_view(template_name='cities/new_city.html'), name='create_city'),
    path('mayors/', views.MayorsView.as_view(template_name='cities/mayors.html'), name='mayors'),
    path('create_mayor/', views.MayorCreateView.as_view(template_name='cities/new_mayor.html'), name='create_mayor'),
    path('new_street/<int:pk>', views.new_street, name='new_street'),
    path('delete_mayor/<int:pk>', views.MayorDelete.as_view(), name='delete_mayor'),
    path('delete_city/<int:pk>', views.CityDelete.as_view(), name='delete_city'),
    path('delete_street/<int:pk>', views.StreetDelete.as_view(), name='delete_street'),
    path('edit_mayor/<int:pk>', views.MayorUpdate.as_view(), name='edit_mayor'),
    path('edit_city/<int:pk>', views.CityUpdate.as_view(), name='edit_city'),
    path('edit_street/<int:pk>', views.StreetUpdate.as_view(), name='edit_street'),
]

cities/models.py
from django.db import models


class Mayor(models.Model):
    """
    Model for creating mayors.
    """
    objects: models.Manager()

    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    date_of_birth = models.DateField()
    date_of_job_start = models.DateField(null=True)

    def __str__(self):
        return self.first_name + ' ' + self.last_name


class City(models.Model):
    """
    Model for creating cities.
    """
    objects: models.Manager()

    name = models.CharField(max_length=40)
    population = models.IntegerField()
    date_of_foundation = models.DateField()
    mayor = models.OneToOneField(Mayor, on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Citie"  # because admin site doesn't recognise english punctuation

    def __str__(self):
        return self.name


class Street(models.Model):
    """
    Model for creating streets for cities.
    """
    objects: models.Manager()

    name = models.CharField(max_length=60)
    city = models.ForeignKey(City, on_delete=models.PROTECT, null=True)

    def __str__(self):
        return self.name

cities/forms.py
from django.forms import ModelForm

from .models import City, Mayor, Street


class CityForm(ModelForm):
    class Meta:
        model = City
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(CityForm, self).__init__(*args, **kwargs)
        self.fields['mayor'].queryset = Mayor.objects.filter(city__isnull=True)


class StreetForm(ModelForm):
    class Meta:
        model = Street
        fields = ['name']

cities/views.py
from django.views.generic import TemplateView, ListView, CreateView, UpdateView, DeleteView, FormView
from django.shortcuts import reverse, redirect, render
from django.urls import reverse_lazy

from .models import City, Mayor, Street
from .forms import CityForm, StreetForm


class IndexView(TemplateView):
    template_name = 'index.html'


class CitiesView(ListView):
    template_name = 'cities/cities.html'
    model = City
    context_object_name = 'cities'

    def get_context_data(self, **kwargs):
        context = super(CitiesView, self).get_context_data(**kwargs)
        context['cities'] = City.objects.all()
        return context


class MayorsView(ListView):
    template_name = 'cities/mayors.html'
    model = Mayor
    context_object_name = 'mayors'


class CityCreateView(CreateView):
    model = City
    form_class = CityForm

    def get_success_url(self):
        return reverse('cities')


class MayorCreateView(CreateView):
    model = Mayor
    fields = ['first_name', 'last_name', 'date_of_birth']

    def get_success_url(self):
        return reverse('mayors')


class MayorDelete(DeleteView):
    model = Mayor
    success_url = reverse_lazy('mayors')


class CityDelete(DeleteView):
    model = City
    success_url = reverse_lazy('cities')


class StreetDelete(DeleteView):
    model = Street
    success_url = reverse_lazy('cities')


class MayorUpdate(UpdateView):
    model = Mayor
    fields = '__all__'
    success_url = reverse_lazy('mayors')


class CityUpdate(UpdateView):
    model = City
    fields = '__all__'
    success_url = reverse_lazy('cities')


class StreetUpdate(UpdateView):
    model = Street
    fields = '__all__'
    success_url = reverse_lazy('cities')


def new_street(request, pk):
    city = City.objects.get(pk=pk)
    print(city.name)
    if request.method == 'POST':
        form = StreetForm(request.POST)
        if form.is_valid():
            street = form.save(commit=False)
            street.city = city
            street.save()
            return redirect('cities')
    else:
        form = StreetForm(None)
    return render(request, 'cities/new_street.html', {'form': form})

templates/GOFRIENDSTest/cities/cities.html
{% extends 'base.html' %}
{% block content %}
<a href="{% url 'index' %}"><button class="dark-button login-button">Back to main page.</button></a>
<br>
<br>
List of cities, their mayors and streets:

{% for city in cities %}
    <ul>
        <li>Name: {{ city.name }}</li>
        <li>Mayor: {{ city.mayor }}</li>
        <li>Streets:

        {% for street in city.street_set.all %}
            <ul>
                {{ street.name }}
                <a href="{% url 'delete_street' pk=street.pk %}"><button class="dark-button login-button">Delete street</button></a>
                <a href="{% url 'edit_street' pk=street.pk %}"><button class="dark-button login-button">Edit street</button></a>
            </ul>
        {% endfor %}
        <a href="{% url 'new_street' pk=city.pk %}"><button class="dark-button login-button">Add a street to this city</button></a>
        <a href="{% url 'delete_city' pk=city.pk %}"><button class="dark-button login-button">Delete city</button></a>
        <a href="{% url 'edit_city' pk=city.pk %}"><button class="dark-button login-button">Edit city information</button></a>
        </li>

    </ul>
    <p>--------------------------------------------</p>
{% endfor %}
Add a new city: <a href="{% url 'create_city' %}"><button class="dark-button login-button">+</button></a>
{% endblock %}

templates/GOFRIENDSTest/cities/city_confirm_delete.html
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    {{ form }}
    <input type="submit" value="Confirm">
</form>

templates/GOFRIENDSTest/cities/city_form.html
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>

templates/GOFRIENDSTest/cities/index.html
{% extends 'base.html' %}
{% block content %}
This is a main page.
<br>
<a href="{% url 'logout' %}"><button class="dark-button login-button">Logout</button></a>
<a href="{% url 'cities' %}"><button class="dark-button login-button">Cities</button></a>
<a href="{% url 'mayors' %}"><button class="dark-button login-button">Mayors</button></a>
{% endblock %}

templates/GOFRIENDSTest/cities/mayor_confirm_delete.html
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    {{ form }}
    <input type="submit" value="Confirm">
</form>

templates/GOFRIENDSTest/cities/mayor_form.html
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>

templates/GOFRIENDSTest/cities/mayors.html
{% extends 'base.html' %}
{% block content %}
<a href="{% url 'index' %}"><button class="dark-button login-button">Back to main page.</button></a>
<br>
<br>
List of mayors and their cities:
{% for mayor in mayors %}
    <p>Name: {{ mayor.first_name }} {{ mayor.last_name }}:</p>
    <p>Mayor of city:
        {% if mayor.city %}
            {{ mayor.city }}
        {% else %}
            not a mayor of a city yet
        {% endif %}
    <br>
    <a href="{% url 'delete_mayor' mayor.pk %}"><button class="dark-button login-button">Delete Mayor</button></a>
    <a href="{% url 'edit_mayor' mayor.pk %}"><button class="dark-button login-button">Edit Mayor</button></a>

<p>---------------------------------------</p>
{% endfor %}
Add a new mayor: <a href="{% url 'create_mayor' %}"><button class="dark-button login-button">+</button></a>
{% endblock %}

templates/GOFRIENDSTest/cities/new_city.html
{% extends "base.html" %}
{% block content %}
<a href="{% url 'index' %}"><button class="dark-button login-button">Back to main page.</button></a>

<form method="post">{% csrf_token %}
    <p>Name: {{ form.name }}</p>
    <p>Population: {{ form.population }}</p>
    <p>Mayor: {{ form.mayor }}</p>
    <p>Date of foundation: {{ form.date_of_foundation }} [yyyy-mm-dd]</p>
    <input type="submit" value="Save">
</form>
{% endblock %}

templates/GOFRIENDSTest/cities/new_mayor.html
{% extends "base.html" %}
{% block content %}
<a href="{% url 'index' %}"><button class="dark-button login-button">Back to main page.</button></a>

<form method="post">{% csrf_token %}
    <p>First name: {{ form.first_name }}</p>
    <p>Last name: {{ form.last_name }}</p>
    <p>Date of birth: {{ form.date_of_birth }} [yyyy-mm-dd]</p>
    <input type="submit" value="Save">
</form>
{% endblock %}

templates/GOFRIENDSTest/cities/new_street.html
{% extends "base.html" %}
{% block content %}
<a href="{% url 'index' %}"><button class="dark-button login-button">Back to main page.</button></a>

<form method="post">{% csrf_token %}
    <p>Name: {{ form.name }}</p>
    {{ form.errors }}
    <input type="submit" value="Save">
</form>
{% endblock %}

templates/GOFRIENDSTest/cities/street_confirm_delete.html
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    {{ form }}
    <input type="submit" value="Confirm">
</form>

templates/GOFRIENDSTest/cities/street_form.html
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>